Controllers/JogadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto.NET.Models;
using Projeto_.NET.Models;

namespace Projeto.NET.Controllers
{
    public class JogadorController : Controller
    {
        JogadorDALL jogadorDALL = new JogadorDALL();
        public IActionResult Index()
        {
            List<Jogador> JList = new List<Jogador>();
            JList = jogadorDALL.GetAllJogador().ToList();
            return View(JList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] Jogador obj_jogador)
        {
            if (ModelState.IsValid)
            {
                jogadorDALL.AddJogador(obj_jogador);
                return RedirectToAction("Index");
            }
            return View(obj_jogador);
        }

         
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Jogador J1 = jogadorDALL.GetJogadorById(id);
            if (J1 == null)
            {
                return NotFound();
            }
            
            return View(J1);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, [Bind] Jogador obj_Jogador)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                jogadorDALL.UpdateJogador(obj_Jogador);
                return RedirectToAction("Index");
            }
            return View(jogadorDALL);
        }
        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Jogador J1 = jogadorDALL.GetJogadorById(id);
            if (J1 == null)
            {
                return NotFound();
            }
            return View(J1);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Jogador J1 = jogadorDALL.GetJogadorById(id);
            if (J1 == null)
            {
                return NotFound();
            }
            return View(J1);
        }


        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteJ1(int? id)
        {
            jogadorDALL.DeleteJogador(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto Ness</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>


<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto Ness</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jogador" asp-action="Index">Criar Jogador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2020 - Projeto_.NET_CORE - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>